apiVersion: v2
description: Kubernetes logging stack with Opensearch
name: kubernetes-logging
version: 3.7.0
maintainers:
  - name: Niki Dokovski
    email: nickytd@gmail.com
    url: https://github.com/nickytd