{{ if .Values.journalbeat.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-journalbeat
  labels: {{ include "logging.labels" . | indent 4 }}
    type: journalbeat
spec:
  selector:
    matchLabels: {{ include "logging.selectorLabels" . | indent 6 }}
      k8s-app: journalbeat      
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels: {{ include "logging.selectorLabels" . | indent 8 }}
        k8s-app: journalbeat
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/beats/journalbeat-configmap.yaml") . | sha256sum }}      
    spec:
      priorityClassName: {{ default .Values.priority_class .Values.journalbeat.priority_class }}
      securityContext:
        runAsUser: 0
      {{- with .Values.journalbeat.affinity }}     
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.journalbeat.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Release.Name }}-priv
      terminationGracePeriodSeconds: 30
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 6 }}
      {{- end }}
      initContainers:
      - name: init  
        imagePullPolicy: {{ .Values.init_container_image.imagePullPolicy }}
        image: {{ include "init_container.image" . }}
        {{- if .Values.kafka.enabled }}
        command: ["sh","-c",'/init.sh {{ include "es_url" . }} && /init.sh {{ .Release.Name }}-kafka-{{ (sub (.Values.kafka.replicas | int) 1) }}.kafka 9092']
        {{ else }}
        command: ["sh","-c",'/init.sh {{ include "es_url" . }} && /init.sh {{ .Release.Name}}-logstash-indexer 5044']
        {{- end }}
        volumeMounts:
        - mountPath: "/init.sh"
          subPath: init.sh
          name: init 
      containers:
      - name: journalbeat
        image: {{ .Values.elasticsearch.image }}/beats/journalbeat-oss:{{ .Values.elasticsearch.imageTag }}
        args: [
          "-c", "/usr/share/journalbeat/journalbeat.yml",
          "-e"
        ]
        resources: {{ toYaml .Values.journalbeat.resources | nindent 10 }}          
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: config
          mountPath: /usr/share/journalbeat/journalbeat.yml
          readOnly: true
          subPath: journalbeat.yml
        - name: journal-log
          mountPath: /logs
        - name: systemd
          mountPath: /run/systemd
          readOnly: true
        - name: data
          mountPath: /usr/share/journalbeat/data 
      volumes:
      - name: init
        configMap:
          name: {{ .Release.Name}}-init
          defaultMode: 0755  
      - name: config
        configMap:
          name: {{ .Release.Name}}-journalbeat-config
      - name: journal-log
        hostPath:
          path: {{ .Values.journalbeat.journals_host_path }}
          type: Directory
      - name: systemd
        hostPath:
          path: /run/systemd 
      - name: data
        emptyDir: {}
{{ end }}
