apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name}}-fluent-bit
  labels: {{ include "logging.labels" . | indent 4 }}
    k8s-app: fluent-bit
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |-
    [SERVICE]
        Flush                         1
        Log_Level                     debug
        Daemon                        off
        Parsers_File                  parsers.conf
        HTTP_Server                   On
        HTTP_Listen                   0.0.0.0
        HTTP_Port                     2020
        net.connect_timeout_log_error true
        net.connect_timeout           100
        net.keepalive                 on
        net.keepalive_idle_timeout    60
        net.dns.mode                  TCP
        storage.type                  filesystem
        storage.path                  /var/log/flb-storage/
        storage.sync                  normal
        storage.checksum              off
        storage.backlog.mem_limit     50M
        storage.max_chunks_up         1000
        storage.metrics               on

    @INCLUDE input-stock-*.conf
    @INCLUDE input-custom-*.conf
    @INCLUDE filter-stock-*.conf
    @INCLUDE filter-custom-*.conf
    {{- if .Values.kafka.enabled }}
    @INCLUDE output-stock-kafka.conf
    {{- else }}
    @INCLUDE output-stock-opensearch-*.conf
    {{- end }}
    @INCLUDE output-custom-*.conf

  input-stock-kubernetes.conf: |-
    [INPUT]
        Name              tail
        Tag               kube.<pod_id>.<namespace_name>.<pod_name>.<container_name>
        Tag_Regex         /var/log/pods/(?<namespace_name>[^_/]+)_(?<pod_name>[^_/]+)_(?<pod_id>[^_/]+)/(?<container_name>[^/]+)/.*
        Path              /var/log/pods/*/*/*.log
        DB                /var/log/flb_kube.db
        Exclude_Path      /var/log/pods/*/*/*.gz,/var/log/pods/*/*/*.zip
        Mem_Buf_Limit     50MB
        Buffer_Max_Size   5MB
        Buffer_Chunk_Size 1024k
        Skip_Long_Lines   Off
        Refresh_Interval  10
        Read_from_Head    False
        Log_Level         debug
        multiline.parser  cri, docker, go, python, java

  input-stock-systemd.conf: |-
    [INPUT]
        Name                systemd
        Tag                 systemd.*
        Systemd_Filter      _SYSTEMD_UNIT=kubelet.service
        Systemd_Filter      _SYSTEMD_UNIT={{.Values.fluentbit.containersRuntime}}.service
        Systemd_Filter_Type Or
        Read_From_Tail      On
        Path                /run/log/journal
        Strip_Underscores   On

  filter-stock-kubernetes.conf: |-
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_Tag_Prefix     kube.
        Regex_Parser        kube-tag
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log           On
        Keep_Log            On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Labels              On
        Kube_Meta_Cache_TTL 60s
        Annotations         Off

  filter-stock-de_dot.conf: |-
    [FILTER]
        Name    lua
        Match   kube.*
        script  /fluent-bit/etc/dedot.lua
        call    dedot

  filter-stock-parser.conf: |-
    [FILTER]
        Name                parser
        Match               nginx
        Key_Name            log
        Parser              k8s-nginx-ingress
        Reserve_Data        True

  filter-stock-rewrite.conf: |-
    [FILTER]
        Name          rewrite_tag
        Match         kube.*
        Rule          $kubernetes['labels']['app_kubernetes_io/name'] "^(ingress-nginx)$" nginx false

  output-stock-opensearch-nginx.conf: |-
    [OUTPUT]
        Name                es
        Match               nginx
        Host                ${FLUENT_opensearch_HOST}
        Port                ${FLUENT_opensearch_PORT}
        HTTP_User           ${FLUENT_opensearch_USER}
        HTTP_Passwd         ${FLUENT_opensearch_PASSWORD}
        Logstash_Format     On
        Logstash_Prefix     nginx
        Replace_Dots        On
        Retry_Limit         False
        Trace_Error         On
        Suppress_Type_Name  On
        Include_Tag_Key     Off
        Time_Key_Nanos      Off
        Generate_ID         On
        tls                 On
        tls.Verify          On
        tls.ca_file         /fluent-bit/ssl/root-ca.pem
        tls.crt_file        /fluent-bit/ssl/admin.pem
        tls.key_file        /fluent-bit/ssl/admin-key.pem

  output-stock-opensearch-journals.conf: |-
    [OUTPUT]
        Name                es
        Match               systemd.*
        Host                ${FLUENT_opensearch_HOST}
        Port                ${FLUENT_opensearch_PORT}
        HTTP_User           ${FLUENT_opensearch_USER}
        HTTP_Passwd         ${FLUENT_opensearch_PASSWORD}
        Logstash_Format     On
        Logstash_Prefix     systemd
        Replace_Dots        On
        Retry_Limit         False
        Trace_Error         On
        Suppress_Type_Name  On
        Include_Tag_Key     Off
        Time_Key_Nanos      Off
        Generate_ID         On
        tls                 On
        tls.Verify          On
        tls.ca_file         /fluent-bit/ssl/root-ca.pem
        tls.crt_file        /fluent-bit/ssl/admin.pem
        tls.key_file        /fluent-bit/ssl/admin-key.pem

  output-stock-opensearch-containers.conf: |-
    [OUTPUT]
        Name                es
        Match               kube.*
        Host                ${FLUENT_opensearch_HOST}
        Port                ${FLUENT_opensearch_PORT}
        HTTP_User           ${FLUENT_opensearch_USER}
        HTTP_Passwd         ${FLUENT_opensearch_PASSWORD}
        Logstash_Format     On
        Logstash_Prefix     containers
        Replace_Dots        On
        Retry_Limit         False
        Trace_Error         On
        Suppress_Type_Name  On
        Include_Tag_Key     Off
        Time_Key_Nanos      Off
        Generate_ID         On
        tls                 On
        tls.Verify          On
        tls.ca_file         /fluent-bit/ssl/root-ca.pem
        tls.crt_file        /fluent-bit/ssl/admin.pem
        tls.key_file        /fluent-bit/ssl/admin-key.pem

  output-stock-kafka.conf: |-
    [OUTPUT]
        Name                             kafka
        Match                            *
        Brokers                          {{ include "kafkaBrokers" (dict "replicas" .Values.kafka.replicas "releaseName" $.Release.Name) }}
        Topics                           containers
        Retry_Limit                      False
        timestamp_format                 iso8601
        rdkafka.log.connection.close     false
        rdkafka.request.required.acks    all
        rdkafka.message.max.bytes        10000000
        rdkafka.queue.buffering.max.ms   50
        rdkafka.client.id                ${HOSTNAME}

  dedot.lua: |-
    function dedot(tag, timestamp, record)
      if record["kubernetes"] == nil then
        return 0, 0, 0
      end
      dedot_keys(record["kubernetes"]["annotations"])
      dedot_keys(record["kubernetes"]["labels"])
      return 1, timestamp, record
    end

    function dedot_keys(map)
        if map == nil then
            return
        end
        local new_map = {}
        local changed_keys = {}
        for k, v in pairs(map) do
            local dedotted = string.gsub(k, "%.", "_")
            if dedotted ~= k then
                new_map[dedotted] = v
                changed_keys[k] = true
            end
        end
        for k in pairs(changed_keys) do
            map[k] = nil
        end
        for k, v in pairs(new_map) do
            map[k] = v
        end
    end

  parsers.conf: |-
    [PARSER]
        Name        k8s-nginx-ingress
        Format      regex
        Regex       ^(?<host>[^ ]*) - (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*) "(?<referrer>[^\"]*)" "(?<agent>[^\"]*)" (?<request_length>[^ ]*) (?<request_time>[^ ]*) \[(?<proxy_upstream_name>[^ ]*)\] (\[(?<proxy_alternative_upstream_name>[^ ]*)\] )?(?<upstream_addr>[^ ]*) (?<upstream_response_length>[^ ]*) (?<upstream_response_time>[^ ]*) (?<upstream_status>[^ ]*) (?<reg_id>[^ ]*).*$
        Time_Key    time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        # https://github.com/Yolean/fluent-bit-kubernetes-logging/blob/kustomize-base/base/parser-cri.conf#L9
        Name        kube-tag
        Format      regex
        Regex       ^(?<pod_id>[^.]+)\.(?<namespace_name>[^.]+)\.(?<pod_name>[^.]+)\.(?<container_name>[^.]+)$

    [PARSER]
        Name        syslog
        Format      regex
        Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key    time
        Time_Format %b %d %H:%M:%S

    # Appending any additional parsers from fluentbit-custom-files
    # parsers.conf must be the LAST file as parsers.conf 
    # does NOT support the @INCLUDE syntax to append more.
    #
    # Using regexMatch (and others) from https://github.com/Masterminds/sprig/blob/master/regex.go

{{- range $path, $_ := .Files.Glob "fluentbit-custom-files/*" }}
{{- if $path | regexMatch ".*parser.*" }}
{{ printf "" | nindent 4 }}
{{ printf "#%s" $path | nindent 4 }}
{{ $.Files.Get $path | indent 4 }}
{{- end }}
{{- end }}

{{- range $path, $_ := .Files.Glob "fluentbit-custom-files/*" }}
{{- if not ($path | regexMatch ".*parser.*") }}
{{ regexReplaceAll "(.*)/" $path "" | indent 2 }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
{{- end }}
