{{- if and .Values.kafka.enabled .Values.logstash.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name}}-logstash
  labels: {{ include "logging.labels" . | indent 4 }}
data:
{{- range $path, $bytes := .Files.Glob "index-pipelines/*.*" }}
{{- $name := base (dir $path) }}
{{ base $path | indent 2}}: |-
{{ (tpl ($.Files.Get $path) $)| indent 4 }}
{{ end }}

  pipelines.yml: |-
{{- range $path, $bytes := .Files.Glob "index-pipelines/*-pipeline.conf" }}
    - pipeline.id: {{ printf "%s" (base $path) }}
      pipeline.workers: 2
      path.config: {{ printf "%s%s" "/usr/share/logstash/pipeline/" (base $path) }}
      pipeline.ecs_compatibility: disabled
{{ end }}

  log4j2.properties: |-
    status = error
    name = LogstashPropertiesConfig

    appender.console.type = Console
    appender.console.name = plain_console
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c] %m%n

    appender.json_console.type = Console
    appender.json_console.name = json_console
    appender.json_console.layout.type = JSONLayout
    appender.json_console.layout.compact = true
    appender.json_console.layout.eventEol = true

    rootLogger.level = ${sys:ls.log.level}

    rootLogger.appenderRef.console.ref = ${sys:ls.log.format}_console

    logger.opensearch_output.name = logstash.outputs.opensearch
    logger.opensearch_output.level = warn

    logger.inputs_kafka.name=logstash.inputs.kafka
    logger.inputs_kafka.level=error

    logger.filters_json.name=logstash.filters.json
    logger.filters_json.level=error

    #slowlog.threshold.warn: 2s
    #slowlog.threshold.info: 1s
    #slowlog.threshold.debug: 500ms
    #slowlog.threshold.trace: 100ms
    
    #logger.inputs.name=logstash.inputs.file
    #logger.inputs.level=warn
    #logger.outputs.name=logstash.outputs.kafka
    #logger.outputs.level=debug
    #logger.pipeline.name=logstash.pipeline
    #logger.pipeline.level=debug
    #logger.grok.name=logstash.filters.grok
    #logger.grok.level=debug
    #logger.mutate.name=logstash.filters.mutate
    #logger.mutate.level=debug

  logstash.yml: |-
    http.host: "0.0.0.0"
    path.settings: /usr/share/logstash/config
    queue.type: persisted
    pipeline.batch.size: 125
    log.format: plain
    log.level: error
 
{{- end }}