apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-priv
  labels: {{ include "logging.labels" . | indent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "logging.labels" . | indent 4 }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "logging.labels" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  - namespaces
  - endpoints
  - pods
  verbs:
  - get
  - watch
  - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "logging.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: {{ .Release.Name }}-priv
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-psp
  labels: {{ include "logging.labels" . | indent 4 }}
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ .Release.Name }}
  verbs:
  - use
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-psp
  labels: {{ include "logging.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-priv
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-psp
  apiGroup: rbac.authorization.k8s.io