{{- $global := . }}
{{- range $i, $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
type: tls
data:
  tls.key: {{ $secret.key | b64enc }}
  tls.crt: {{ $secret.crt | b64enc }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-opensearch-credentials-admin
data:
  username: {{ .Values.opensearch.user | b64enc }}
  password: {{ .Values.opensearch.password | b64enc }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-opensearch-dashboards-credentials-admin
data:
  username: {{ .Values.opensearch_dashboards.user | b64enc }}
  password: {{ .Values.opensearch_dashboards.password | b64enc }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-opensearch-dashboards-credentials-developer
data:
  username: {{ .Values.opensearch_dashboards.developer.user | b64enc }}
  password: {{ .Values.opensearch_dashboards.developer.password | b64enc }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-opensearch-dashboards-credentials-readonly
data:
  username: {{ .Values.opensearch_dashboards.readonly.user | b64enc }}
  password: {{ .Values.opensearch_dashboards.readonly.password | b64enc }}
type: Opaque
