{{- if .Values.opensearch.inCluster }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-curator
  labels: {{ include "logging.labels" . | indent 4 }}
stringData:
  curator.yml: |-
    # Remember, leave a key empty if there is no value.  None will be a string,
    # not a Python "NoneType"
    client:
      hosts:
        - ${os_host}
      url_prefix:
      use_ssl: true
      certificate: /etc/root-ca.pem
      client_cert:
      client_key:
      ssl_no_validate: false
      username: {{ .Values.opensearch.user }}
      password: {{ .Values.opensearch.password }}
      timeout: 300
      master_only: false
    logging:
      loglevel: INFO
      logfile:
      logformat: json
      blacklist: ['urllib3']

{{- end }}
