{{- if and (.Values.data_prepper) (.Values.data_prepper.enabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-data-prepper
  labels: {{ include "logging.labels" . | indent 4 }}
data:
  data-prepper-config.yaml: |-
    ssl: false

  pipelines.yaml: |-
    entry-pipeline:
      workers: 4 
      delay: "100"
      source:
        otel_trace_source:
          ssl: false
          port: 21890
      buffer:
        bounded_blocking:
          buffer_size: 1024 # max number of records the buffer accepts
          batch_size: 256 # max number of records the buffer drains after each read    
      sink:
        - pipeline:
            name: "raw-pipeline"
        - pipeline:
            name: "service-map-pipeline"
    
    raw-pipeline:
      source:
        pipeline:
          name: "entry-pipeline"
      prepper:
        - otel_trace_raw_prepper:
      sink:
        - opensearch:
            hosts: [ {{ include "os_url" . }} ]
            cert: "/usr/share/data-prepper/root-ca.pem"
            username: {{ .Values.opensearch.user }}
            password: {{ .Values.opensearch.password }}
            trace_analytics_raw: true

    service-map-pipeline:
      delay: "100"
      source:
        pipeline:
          name: "entry-pipeline"
      prepper:
        - service_map_stateful:
      sink:
        - opensearch:
            hosts: [ {{ include "os_url" . }} ]
            cert: "/usr/share/data-prepper/root-ca.pem"
            username: {{ .Values.opensearch.user }}
            password: {{ .Values.opensearch.password }}
            trace_analytics_service_map: true
{{- end   }}