{{- if and (.Values.data_prepper) (.Values.data_prepper.enabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-data-prepper
  labels: {{ include "logging.labels" . | indent 4 }}
data:
  data-prepper-config.yaml: |-
    ssl: false
{{- end   }}