{{- if .Values.opensearch.inCluster }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-data
  labels: {{ include "logging.labels" . | indent 4 }}
spec:
  updateStrategy:
    type: RollingUpdate
  serviceName: {{ .Release.Name }}-data
  replicas: {{ .Values.data.replicas }}
  selector:
    matchLabels: {{ include "logging.selectorLabels" . | indent 6 }}
      node: os
      {{- if .Values.opensearch.singleNode }}
      type: single
      {{- else }}
      type: data
      {{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/opensearch/os-configmap.yaml") . | sha256sum }}
        checksum/secret1: {{ include (print $.Template.BasePath "/opensearch/os-in-certificates-sec.yaml") . | sha256sum }}
      labels: {{ include "logging.selectorLabels" . | indent 8 }}
        node: os
        {{- if .Values.opensearch.singleNode }}
        type: single
        {{- else }}
        type: data
        {{- end }}
    spec:
      priorityClassName: {{ default .Values.priorityClass .Values.data.priorityClass }}
      {{- with .Values.data.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.data.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Release.Name }}-priv
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 6 }}
      {{- end }}
      initContainers:
      - name: init
        image: {{ include "init_container.image" . }}
        imagePullPolicy: {{ .Values.init_container.imagePullPolicy }}
        command: ["sh", "-c", "/init/init_os_node.sh "]
        volumeMounts:
        - name: init
          mountPath: init
        - name: os-data
          mountPath: /data
        - name: shared
          mountPath: /shared
        - name: certificates
          mountPath: /config/node-key.pem
          subPath: serverKey
        - name: certificates
          mountPath: /config/ofd-rest-key.pem
          subPath: serverKey
        {{- if .Values.opensearch.snapshot.enabled }}
        - name: os-snapshot
          mountPath: /snapshot
        {{- end }}
        securityContext:
          runAsUser: 0
          privileged: true
      containers:
      - name: main
        image: {{ .Values.opensearch.image }}:{{ .Values.opensearch.imageTag }}
        imagePullPolicy: {{ .Values.opensearch.imagePullPolicy }}
        resources: {{ toYaml .Values.data.resources | nindent 10 }}
        {{- if .Values.opensearch.singleNode }}
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        {{- else}}
        ports:
        - containerPort: 9300
          name: transport
        {{- end }}
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 60
          periodSeconds: 60
        volumeMounts:
        - name: os-data
          mountPath: /data
        {{- if .Values.opensearch.snapshot.enabled }}
        - name: os-snapshot
          mountPath: /snapshot
        {{- end }}
        {{- if .Values.opensearch.singleNode }}
        - name: opensearch
          mountPath: /livenessProbe.sh
          subPath: livenessProbe.sh
        {{- end }}
        - name: opensearchsecret
          mountPath: /usr/share/opensearch/config/opensearch.yml
          subPath: opensearch.yml
        - name: opensearch
          mountPath: /usr/share/opensearch/config/log4j2.properties
          subPath: log4j2.properties
        - name: certificates
          mountPath: /usr/share/opensearch/config/node.pem
          subPath: serverCert
        - name: certificates
          mountPath: /usr/share/opensearch/config/root-ca.pem
          subPath: caCert
        - name: certificates
          mountPath: /usr/share/opensearch/config/ofd-rest.pem
          subPath: serverCert
        - name: shared
          mountPath: /usr/share/opensearch/config/node-key.key
          subPath: node-key.key
        - name: shared
          mountPath: /usr/share/opensearch/config/ofd-rest-key.key
          subPath: ofd-rest-key.key
        env:
        - name: os_url
          value: https://localhost:9200
        - name: os_user
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-opensearch-credentials-admin
              key: username
        - name: os_pass
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-opensearch-credentials-admin
              key: password
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPENSEARCH_JAVA_OPTS
          value: "-Xms{{ .Values.data.heapSize }} -Xmx{{ .Values.data.heapSize }} {{ .Values.opensearch.additionalJvmParams }}"
        {{- if not .Values.opensearch.singleNode }}
        - name: NODE_MASTER
          value: "false"
        {{- end }}
        - name: NODE_DATA
          value: "true"
      volumes:
      - name: init
        configMap:
          name: {{ .Release.Name}}-init
          defaultMode: 0755
      - name: opensearch
        configMap:
          name: {{ .Release.Name }}
          defaultMode: 0755
      - name: opensearchsecret
        secret:
          secretName: {{ .Release.Name }}
          defaultMode: 0644
      {{- if .Values.opensearch.snapshot.enabled }}
      - name: os-snapshot
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-snapshot-pvc
      {{- end }}
      - name: certificates
        secret:
          {{- if .Values.opensearch.inClusterCertificates.secretName }}
          secretName: {{ .Values.opensearch.inClusterCertificates.secretName }}
          {{- else }}
          secretName: {{ .Release.Name }}-cluster-certificates
          {{- end }}
      - name: securityconfig
        secret:
          defaultMode: 0644
          secretName: {{ .Release.Name }}-securityconfig
      - name: shared
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: os-data
    spec:
      {{- if or .Values.storageClass .Values.data.storageClass }}
      storageClassName: {{ default .Values.storageClass .Values.data.storageClass | quote }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.data.storage }}
      accessModes:
      - ReadWriteOnce
{{- end }}
