{{- if and .Values.opensearch.inClusterCertificates.generateCertificates (not .Values.opensearch.inClusterCertificates.secretName) }}
{{ $ca := genCA "logging" 3650 }}
{{ $cn := printf "*.%s.svc.cluster.local" .Release.Namespace }}
{{ $server := genSignedCert $cn nil nil 365 $ca }}
{{ $admin := genSignedCert "admin" nil nil 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cluster-certificates
  labels: {{ include "logging.labels" . | indent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
data:
  caCert: {{ b64enc $ca.Cert }}
  adminCert: {{ b64enc $admin.Cert }}
  adminKey: {{ b64enc $admin.Key }}
  serverCert: {{ b64enc $server.Cert }}
  serverKey: {{ b64enc $server.Key }}
{{ end }}