{{- if and (.Values.opensearch.inCluster) (not .Values.opensearch.singleNode) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name:  {{ .Release.Name }}-master
  labels: {{ include "logging.labels" . | indent 4 }}
    node: os
spec:
  updateStrategy:
    type: RollingUpdate
  serviceName: {{ .Release.Name }}-master
  replicas: {{ .Values.master.replicas }}
  selector:
    matchLabels: {{ include "logging.selectorLabels" . | indent 6 }}
      type: master
      node: os
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/opensearch/os-configmap.yaml") . | sha256sum }}
        checksum/secret1: {{ include (print $.Template.BasePath "/opensearch/os-in-certificates-sec.yaml") . | sha256sum }}
      labels: {{ include "logging.selectorLabels" . | indent 8 }}
        type: master
        node: os
    spec:
      priorityClassName: {{ default .Values.priorityClass .Values.master.priorityClass }}
      {{- with .Values.master.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.master.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Release.Name }}-priv
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 6 }}
      {{- end }}
      initContainers:
      - name: init
        image: {{ include "init_container.image" . }}
        imagePullPolicy: {{ .Values.init_container.imagePullPolicy }}
        command: ["sh", "-c", "/init/init_os_node.sh "]
        volumeMounts:
        - name: init
          mountPath: /init
        - name: shared
          mountPath: /shared
        - name: certificates
          mountPath: /config/node-key.pem
          subPath: serverKey
        - name: certificates
          mountPath: /config/ofd-rest-key.pem
          subPath: serverKey
        - name: os-data
          mountPath: /data
        {{- if .Values.opensearch.snapshot.enabled }}
        - name: os-snapshot
          mountPath: /snapshot
        {{- end }}
        securityContext:
          privileged: true
          runAsUser: 0
      containers:
      - name: main
        image: {{ .Values.opensearch.image }}:{{ .Values.opensearch.imageTag }}
        imagePullPolicy: {{ .Values.opensearch.imagePullPolicy }}
        resources: {{ toYaml .Values.master.resources | nindent 10 }}
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 60
          periodSeconds: 60
        ports:
        - containerPort: 9300
          name: transport
        volumeMounts:
        - name: os-data
          mountPath: /data
        {{- if .Values.opensearch.snapshot.enabled }}
        - name: os-snapshot
          mountPath: /snapshot
        {{- end }}
        - name: opensearchsecret
          mountPath: /usr/share/opensearch/config/opensearch.yml
          subPath: opensearch.yml
        - name: opensearch
          mountPath: /usr/share/opensearch/config/log4j2.properties
          subPath: log4j2.properties
        - name: certificates
          mountPath: /usr/share/opensearch/config/node.pem
          subPath: serverCert
        - name: certificates
          mountPath: /usr/share/opensearch/config/root-ca.pem
          subPath: caCert
        - name: certificates
          mountPath: /usr/share/opensearch/config/ofd-rest.pem
          subPath: serverCert
        - name: shared
          mountPath: /usr/share/opensearch/config/node-key.key
          subPath: node-key.key
        - name: shared
          mountPath: /usr/share/opensearch/config/ofd-rest-key.key
          subPath: ofd-rest-key.key
        env:
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPENSEARCH_JAVA_OPTS
          value: "-Xms{{ .Values.master.heapSize }} -Xmx{{ .Values.master.heapSize }} {{ .Values.opensearch.additionalJvmParams }}"
        - name: NODE_DATA
          value: "false"
        - name: NODE_INGEST
          value: "false"
        - name: NODE_MASTER
          value: "true"
      volumes:
      - name: init
        configMap:
          name: {{ .Release.Name}}-init
          defaultMode: 0755
      - name: opensearch
        configMap:
          name: {{ .Release.Name }}
      - name: opensearchsecret
        secret:
          secretName: {{ .Release.Name }}
      {{- if .Values.opensearch.snapshot.enabled }}
      - name: os-snapshot
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-snapshot-pvc
      {{- end }}
      - name: certificates
        secret:
          {{- if .Values.opensearch.inClusterCertificates.secretName }}
          secretName: {{ .Values.opensearch.inClusterCertificates.secretName }}
          {{- else }}
          secretName: {{ .Release.Name }}-cluster-certificates
          {{- end}}
      - name: securityconfig
        secret:
          secretName: {{ .Release.Name }}-securityconfig
      - name: shared
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: os-data
    spec:
      {{- if or .Values.storageClass .Values.master.storageClass }}
      storageClassName: {{ default .Values.storageClass .Values.master.storageClass | quote }}
      {{- end }}
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.master.storage }}
{{- end }}
