{{- if .Values.opensearch.snapshot.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-snapshot-pvc
  labels: {{ include "logging.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.opensearch.snapshot.size }}
  {{- if or .Values.storageClass .Values.opensearch.snapshot.storageClass }}
  storageClassName: {{ default .Values.storageClass .Values.opensearch.snapshot.storageClass | quote }}
  {{- end }}
{{- end}}