{{- if .Values.elasticsearch.in_cluster }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-aliases
  labels: {{ include "logging.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "-7"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  backoffLimit: 10
  template:
    metadata:
      annotations:
        "sidecar.istio.io/inject": "false"
      labels: {{ include "logging.selectorLabels" . | indent 8 }}            
        type: es-aliases
    spec:
      restartPolicy: OnFailure
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 6 }}
      {{- end }}
      initContainers:
      - name: init
        image: {{ include "init_container.image" . }}
        imagePullPolicy: {{ .Values.init_container.imagePullPolicy }}
        command: ["sh", "-c", "/init.sh {{ .Release.Name }}-client 9200 && /init.sh {{ .Release.Name }}-master-{{ (sub (.Values.master.replicas | int) 1) }} 9300"]
        volumeMounts:
        - mountPath: "/init.sh"
          subPath: init.sh
          name: init
      containers: 
      - name: es-curator
        image: {{ .Values.es_curator.image }}:{{ .Values.es_curator.imageTag }}
        env:
        - name: ES_HOST
          value: {{ include "es_url" . }}
        command: ["/curator/curator", "--config", "/config/curator.yml", "/config/actions.yml"]
        volumeMounts:
        - name: curator
          mountPath: "/config"
        - name: certificates
          mountPath: /etc/root-ca.pem
          subPath: root-ca.pem
      volumes:
      - name: init
        configMap:
          name: {{ .Release.Name}}-init
          defaultMode: 0755  
      - name: curator
        configMap:
          name: {{ .Release.Name }}-curator
      - name: certificates
        secret:
          secretName: {{ .Release.Name }}-certificates     
{{- end }}