{{- if .Values.elasticsearch.in_cluster }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-curator
  labels: {{ include "logging.labels" . | indent 4 }}
spec:
  schedule: "10 0 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            "sidecar.istio.io/inject": "false"
          labels: {{ include "logging.labels" . | indent 12 }}            
            type: es-curator
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets: {{ toYaml . | nindent 10 }}
          {{- end }}
          initContainers:
          - name: init
            image: {{ include "init_container.image" . }}
            imagePullPolicy: {{ .Values.init_container.imagePullPolicy }}
            command: ["sh", "-c", "/init/check_es.sh"]
            env:
            - name: es_url
              value: {{ include "es_url" . }}
            - name: es_user
              value: {{ .Values.elasticsearch.user }}
            - name: es_pass
              value: {{ .Values.elasticsearch.password }}
            volumeMounts:
            - mountPath: "/init"
              name: init
          containers:
          - name: es-curator
            image: {{ .Values.es_curator.image }}:{{ .Values.es_curator.imageTag }}
            env:
            - name: ES_HOST
              value: {{ include "es_url" . }}
            command: ["/curator/curator", "--config", "/config/curator.yml", "/config/actions.yml"]
            volumeMounts:
            - name: curator
              mountPath: "/config"
            - name: certificates
              mountPath: /etc/root-ca.pem
              subPath: root-ca.pem  
          restartPolicy: OnFailure
          volumes:
          - name: init
            configMap:
              name: {{ .Release.Name}}-init
              defaultMode: 0755 
          - name: curator
            configMap:
              name: {{ .Release.Name }}-curator
          - name: certificates
            secret:
              secretName: {{ .Release.Name }}-certificates
{{- end }}              
