apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-index-templates
data:
{{- range $path, $bytes := .Files.Glob "indices-templates/*.json" }}
{{- $name := base (dir $path) }}  
{{ base $path | indent 2}}: |-
{{ (tpl ($.Files.Get $path) $)| indent 4 }}
{{- end }}
  templates.sh: |-
    #!/bin/bash

    set -e     

    echo "seting up index templates"
    if [ -z ${es_url+x} ]; then
      echo "elasticsearch url env variable (es_url) is expected but not found";
      exit -1
    elif [ -z ${es_user+x} ]; then
      echo "elasticsearch user env variable (es_user) is expected but not found";
      exit -1
    elif [ -z ${es_pass+x} ]; then
      echo "elasticsearch password env variable (es_pass) is expected but not found";
      exit -1
    fi


    for file in /templates/*.json ; do
      echo "processing template $file"
      result=`curl -sk -w "%{http_code}" -X PUT -H "Content-Type: application/json" \
        -u$es_user:$es_pass $es_url/_template/${file##*/}_1? -d @$file`

      echo "$result"
    done



