{{- if .Values.elasticsearch.in_cluster }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name:  {{ .Release.Name }}-master
  labels: {{ include "logging.labels" . | indent 4 }}
    node: es
spec:
  updateStrategy:
    type: RollingUpdate
  serviceName: {{ .Release.Name }}-master
  replicas: {{ .Values.master.replicas }}
  selector:
    matchLabels: {{ include "logging.selectorLabels" . | indent 6 }}
      type: master
      node: es
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/elasticsearch/es-configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/elasticsearch/es-certificates-sec.yaml") . | sha256sum }}
      labels: {{ include "logging.selectorLabels" . | indent 8 }}
        type: master
        node: es
    spec:
      priorityClassName: {{ default .Values.priority_class .Values.master.priority_class }}
      {{- with .Values.master.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.master.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Release.Name }}-priv
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: main
        image: {{ .Values.opendistro.image }}:{{ .Values.opendistro.imageTag }}
        resources: {{ toYaml .Values.master.resources | nindent 10 }}
        ports:
        - containerPort: 9300
          name: transport
        - containerPort: 9200
          name: http
        - containerPort: 9600
          name: metrics
        volumeMounts:
        - name: es-data
          mountPath: /data
        {{- if .Values.elasticsearch.snapshot.enabled }}
        - name: es-snapshot
          mountPath: /snapshot
        {{- end }}          
        - name: elasticsearch
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: elasticsearch
          mountPath: /usr/share/elasticsearch/config/log4j2.properties
          subPath: log4j2.properties  
        - name: certificates
          mountPath: /usr/share/elasticsearch/config/node.pem
          subPath: node.pem
        - name: certificates
          mountPath: /usr/share/elasticsearch/config/node-key.pem
          subPath: node-key.pem
        - name: certificates
          mountPath: /usr/share/elasticsearch/config/root-ca.pem
          subPath: root-ca.pem
        - name: certificates
          mountPath: /usr/share/elasticsearch/config/elk-rest.pem
          subPath: elk-rest.pem
        - name: certificates
          mountPath: /usr/share/elasticsearch/config/elk-rest-key.pem
          subPath: elk-rest-key.pem
        - name: certificates
          mountPath: /usr/share/elasticsearch/config/elasticsearch.truststore
          subPath: elasticsearch.truststore  
        - name: certificates
          mountPath: /usr/share/elasticsearch/config/http.truststore
          subPath: http.truststore  
        - name: certificates
          mountPath: /usr/share/elasticsearch/config/keystore.jks
          subPath: keystore.jks        
        env:
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "MINIMUM_MASTER_NODES"
          value: {{ .Values.master.minimum_nodes | quote }}
        - name: ES_JAVA_OPTS
          value: "-Xms{{ .Values.master.heap_size }} -Xmx{{ .Values.master.heap_size }} {{ .Values.elasticsearch.additional_jvm_params }}"
        - name: NODE_DATA
          value: "false"
        - name: NODE_INGEST
          value: "false"
        - name: NODE_MASTER
          value: "true"  
        - name: discovery.seed_hosts
          value: {{ .Release.Name }}-master  
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 10
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 60
          periodSeconds: 10
      volumes:
      - name: elasticsearch
        configMap:
          name: {{ .Release.Name }}
      {{- if .Values.elasticsearch.snapshot.enabled }}
      - name: es-snapshot
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-snapshot-pvc
      {{- end }}    
      - name: certificates
        secret:
          secretName: {{ .Release.Name }}-certificates
      - name: securityconfig
        secret:
          secretName: {{ .Release.Name }}-securityconfig    
      # Elasticsearch requires vm.max_map_count to be at least 262144.
      # If your OS already sets up this number to a higher value, feel free
      # to remove this init container.
      initContainers:
      - name: init
        image: {{ include "init_container.image" . }}
        imagePullPolicy: {{ .Values.init_container_image.imagePullPolicy }}
        command: ["sh","-c","/sbin/sysctl -w vm.max_map_count=262144 || true && chown 1000:1000 /data && if [ -d /snapshot ]; then chown 1000:1000 /snapshot ; fi"]
        volumeMounts:
        - name: es-data
          mountPath: /data
        {{- if .Values.elasticsearch.snapshot.enabled }}
        - name: es-snapshot
          mountPath: /snapshot
        {{- end }}          
        securityContext:
          privileged: true  
          runAsUser: 0
  volumeClaimTemplates:
  - metadata:
      name: es-data
    spec:
      storageClassName: {{ default .Values.storage_class .Values.master.storage_class | quote }}
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.master.storage }}
{{- end }}
