{{- if .Values.elasticsearch.in_cluster }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-aliases
  labels: {{ include "logging.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "-8"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  backoffLimit: 3
  template:
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 12 }}
      {{- end }}
      containers:
      - name: es-curator
        image: {{ .Values.es_curator_image.image }}:{{ .Values.es_curator_image.imageTag }}
        env:
        - name: ES_HOST
          value: {{ include "esurl" . }}
        command: ["/curator/curator", "--config", "/config/curator.yml", "/config/actions.yml"]
        volumeMounts:
        - name: curator
          mountPath: "/config"
        - name: certificates
          mountPath: /etc/root-ca.pem
          subPath: root-ca.pem  
      restartPolicy: OnFailure
      volumes:
      - name: curator
        configMap:
          name: {{ .Release.Name }}-curator
      - name: certificates
        secret:
          secretName: {{ .Release.Name }}-certificates     
{{- end }}          