{{- if .Values.elasticsearch.in_cluster }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-data
  labels: {{ include "logging.labels" . | indent 4 }}
spec:
  updateStrategy:
    type: RollingUpdate
  serviceName: {{ .Release.Name }}-data
  replicas: {{ .Values.data.replicas }}
  selector:
    matchLabels: {{ include "logging.metadata.labels" . | indent 6 }}
      node: es
      type: data
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/elasticsearch/es-configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/elasticsearch/es-certificates-sec.yaml") . | sha256sum }}
      labels: {{ include "logging.metadata.labels" . | indent 8 }}
        node: es
        type: data
    spec:
      priorityClassName: logging-critical
      {{- with .Values.data.affinity }}     
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.data.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Release.Name }}-priv
      priorityClassName: logging-critical
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: main
        image: {{ .Values.opendistro.image }}:{{ .Values.opendistro.imageTag }}
        resources: {{ toYaml .Values.data.resources | nindent 10 }}
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 60
          periodSeconds: 10
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: es-data
          mountPath: /data
        {{- if .Values.elasticsearch.snapshot.enabled }}
        - name: es-snapshot
          mountPath: /snapshot
        {{- end }}          
        - name: elasticsearch
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: elasticsearch
          mountPath: /usr/share/elasticsearch/config/log4j2.properties
          subPath: log4j2.properties  
        - name: certificates
          mountPath: /usr/share/elasticsearch/config/node.pem
          subPath: node.pem
        - name: certificates
          mountPath: /usr/share/elasticsearch/config/node-key.pem
          subPath: node-key.pem
        - name: certificates
          mountPath: /usr/share/elasticsearch/config/root-ca.pem
          subPath: root-ca.pem
        - name: certificates
          mountPath: /usr/share/elasticsearch/config/elk-rest.pem
          subPath: elk-rest.pem
        - name: certificates
          mountPath: /usr/share/elasticsearch/config/elk-rest-key.pem
          subPath: elk-rest-key.pem
        - name: certificates
          mountPath: /usr/share/elasticsearch/config/elasticsearch.truststore
          subPath: elasticsearch.truststore
        - name: certificates
          mountPath: /usr/share/elasticsearch/config/http.truststore 
          subPath: http.truststore        
        env:
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "MINIMUM_MASTER_NODES"
          value: {{ .Values.master.minimum_nodes | quote }}
        - name: ES_JAVA_OPTS
          value: "-Xms{{ .Values.data.heap_size }} -Xmx{{ .Values.data.heap_size }} {{ .Values.elasticsearch.additional_jvm_params }}"
        - name: NODE_MASTER
          value: "false"  
        - name: discovery.seed_hosts
          value: {{ .Release.Name }}-master  
      volumes:
      - name: elasticsearch
        configMap:
          name: {{ .Release.Name }}
{{- if .Values.elasticsearch.snapshot.enabled }}
      - name: es-snapshot
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-snapshot-pvc
{{- end }}  
      - name: certificates
        secret:
          secretName: {{ .Release.Name }}-certificates
      - name: securityconfig
        secret:
          secretName: {{ .Release.Name }}-securityconfig    
      # Elasticsearch requires vm.max_map_count to be at least 262144.
      # If your OS already sets up this number to a higher value, feel free
      # to remove this init container.
      initContainers:
      - name: init
        image: {{ include "init_container.image" . }}
        imagePullPolicy: {{ .Values.init_container_image.imagePullPolicy }}
        command: ["sh", "-c", "/sbin/sysctl -w vm.max_map_count=262144 || true && chown 1000:1000  /data && if [ -d /snapshot ]; then chown 1000:1000 /snapshot ; fi"]
        volumeMounts:
        - name: es-data
          mountPath: /data
        {{- if .Values.elasticsearch.snapshot.enabled }}
        - name: es-snapshot
          mountPath: /snapshot
        {{- end }}           
        securityContext:
          runAsUser: 0
          privileged: true    
  volumeClaimTemplates:
  - metadata:
      name: es-data
    spec:
      {{- if .Values.data.storage_class }}
      storageClassName: {{ .Values.data.storage_class | quote }}
      {{ else }}
      storageClassName: {{ .Values.storage_class | quote }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.data.storage }}
      accessModes:
      - ReadWriteOnce
{{- end }}
