{{- if .Values.elasticsearch.snapshot.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-snapshot-pvc
  labels: {{ include "logging.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.elasticsearch.snapshot.size }}
  {{- if .Values.elasticsearch.snapshot.storage_class }}
  storageClassName: {{ .Values.elasticsearch.snapshot.storage_class | quote }}
  {{ else }}
  storageClassName: {{ .Values.storage_class | quote }}
  {{- end }}
{{- end}}