{{- if .Values.elasticsearch.in_cluster }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-securityconfig
  labels:
{{- include "logging.labels" . | indent 2}}
type: Opaque
data:
{{- range $path, $bytes := .Files.Glob "securityconfig/*" }}
{{- $name := base (dir $path) }}  
{{ base $path | indent 2}}: |-
{{ (tpl ($.Files.Get $path) $)| b64enc | indent 4 }}
{{ end }}
{{- end }}