apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-kibana
  labels: {{ include "logging.labels" . | indent 4 }}
data:
  kibana.yml: |-
    server.name: kibana
    server.host: "0"

    logging.quiet: true
    logging.verbose: false
    logging.json: false

    elasticsearch.logQueries: false
    elasticsearch.hosts: {{ include "es_url" . }}
    elasticsearch.ssl.verificationMode: none
    elasticsearch.username: {{ .Values.kibana.user }}
    elasticsearch.password: {{ .Values.kibana.password }}
    elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization"]

    # Optional settings that provide the paths to the PEM-format SSL certificate and key files.
    # These files are used to verify the identity of Kibana to Elasticsearch and are required when
    # xpack.security.http.ssl.client_authentication in Elasticsearch is set to required.
    #elasticsearch.ssl.certificate: /opt/kibana/config/admin.pem
    #elasticsearch.ssl.key: /opt/kibana/config/admin-key.pem

    # Optional setting that enables you to specify a path to the PEM file for the certificate
    # authority for your Elasticsearch instance.
    elasticsearch.ssl.certificateAuthorities:
    - /opt/kibana/config/root-ca.pem

    newsfeed.enabled: false
    telemetry.optIn: false
    telemetry.enabled: false

    opendistro_security.readonly_mode.roles: ["kibana_read_only"]

{{ if .Values.opendistro.saml.enabled }}    
    server.xsrf.whitelist: ["/_opendistro/_security/saml/acs", "/_opendistro/_security/saml/logout"]
    opendistro_security.auth.type: "saml"
{{ end }}    

    opendistro_security.multitenancy.enabled: true
    opendistro_security.multitenancy.tenants.enable_global: true
    opendistro_security.multitenancy.tenants.enable_private: true
    opendistro_security.multitenancy.tenants.preferred: ["Developer","Global","Private"]
    opendistro_security.cookie.secure: false