{{- if .Values.kibana.in_cluster }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kibana
  labels: {{ include "logging.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.kibana.replicas }}
  selector:
    matchLabels: {{ include "logging.selectorLabels" . | indent 6 }}
      type: kibana
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/kibana/kibana-configmap.yaml") . | sha256sum }}
      labels: {{ include "logging.selectorLabels" . | indent 8 }}
        type: kibana
    spec:
      priorityClassName: {{ default .Values.priority_class .Values.kibana.priority_class }}
      {{- with .Values.kibana.affinity }}     
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kibana.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 6 }}
      {{- end }}
      initContainers:
      - name: init
        image: {{ include "init_container.image" . }}
        imagePullPolicy: {{ .Values.init_container.imagePullPolicy }}
        command: ["sh", "-c", "/init/check_es.sh"]
        env:
          - name: es_url
            value: {{ include "es_url" . }}
          - name: es_user
            value: {{ .Values.elasticsearch.user }}
          - name: es_pass
            value: {{ .Values.elasticsearch.password }}          
        volumeMounts:
        - mountPath: "/init"
          name: init
      containers: 
      - name: main
        image: {{ .Values.opendistro.image }}-kibana:{{ .Values.opendistro.imageTag }}
        resources: {{- toYaml .Values.kibana.resources | nindent 10 }}
        env:
        {{- if .Values.kibana.server_base_path }}
        - name: SERVER_BASEPATH
          value: {{ .Values.kibana.server_base_path }}  
        {{- end }}   
        {{- if .Values.kibana.extraEnvs }}
          {{- toYaml .Values.kibana.extraEnvs | nindent 8 }}
        {{- end }}
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
        volumeMounts:
        - mountPath: "/opt/kibana/config/kibana.yml"
          subPath: kibana.yml
          name: config
        - name: certificates
          mountPath: /opt/kibana/config/root-ca.pem
          subPath: root-ca.pem  
        - name: certificates
          mountPath: /opt/kibana/config/admin.pem
          subPath: admin.pem  
        - name: certificates
          mountPath: /opt/kibana/config/admin-key.pem
          subPath: admin-key.pem         
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}-kibana
      - name: init
        configMap:
          name: {{ .Release.Name}}-init
          defaultMode: 0755
      - name: certificates
        secret:
          secretName: {{ .Release.Name }}-certificates        
{{- end }}
