apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-kibana
  labels: {{ include "logging.labels" . | indent 4 }}
data:
  kibana.yml: |-
    server.name: kibana
    server.host: "0"

    logging.quiet: false
    logging.verbose: false
    logging.json: false

    elasticsearch.logQueries: true
    elasticsearch.hosts: {{ include "es_url" . }}
    elasticsearch.ssl.verificationMode: none
    elasticsearch.username: {{ .Values.kibana.user }}
    elasticsearch.password: {{ .Values.kibana.password }}
    elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization"]
    
    # Optional setting that enables you to specify a path to the PEM file for the certificate
    # authority for your Elasticsearch instance.
    elasticsearch.ssl.certificateAuthorities:
    - /opt/kibana/config/root-ca.pem

    newsfeed.enabled: false
    telemetry.optIn: false
    telemetry.enabled: false

    security.showInsecureClusterWarning: false

    opendistro_security.readonly_mode.roles: ["kibana_read_only"]

{{ if .Values.opendistro.saml.enabled }}    
    server.xsrf.whitelist: ["/_opendistro/_security/saml/acs", "/_opendistro/_security/saml/logout"]
    opendistro_security.auth.type: "saml"
{{ end }}    

    opendistro_security.multitenancy.enabled: true
    opendistro_security.multitenancy.tenants.enable_global: true
    opendistro_security.multitenancy.tenants.enable_private: true
    opendistro_security.multitenancy.tenants.preferred: ["Developer","Global","Private"]
    opendistro_security.cookie.secure: false