apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-kibana-index-pattern
  labels: {{ include "logging.labels" . | indent 4 }}
data:
  check_kibana.sh: |-
    #!/bin/bash
    
    echo "KIBANA URL: $KIBANA_URL"

    state="down"
    while [[ ! $state =~ "green" ]]; do
      state=`curl -sS -X GET -u$KIBANA_USER:$KIBANA_PASSWORD \
        $KIBANA_URL/api/status | jq '.status.overall.state'`
      echo "kibana overall state $state"
      sleep 2
    done  

    echo "kibana is up"
      
  create_index_pattern.sh: |-
    #!/bin/bash

    echo "KIBANA URL: $KIBANA_URL"
    echo "KIBANA USER: $KIBANA_USER"
    echo "KIBANA PASSWORD: $KIBANA_PASSWORD"
    echo "KIBANA DEVELOPER USER: $KIBANA_DEVELOPER_USER"
    echo "KIBANA DEVELOPER PASSWORD: $KIBANA_DEVELOPER_PASSWORD"
    echo "INDEX_PATTERNS: $INDEX_PATTERNS"
    echo "TENANTS: $TENANTS"
    
    if [ -z $INDEX_PATTERNS ]; then 
      echo "no index patterns defined"
      exit 0
    fi  
    
    IFS=',' read -ra PATTERNS <<< "$INDEX_PATTERNS"
    IFS=',' read -ra TENANTS <<< "$TENANTS"

    version=`curl -sS -X GET -u$KIBANA_USER:$KIBANA_PASSWORD \
        $KIBANA_URL/api/status | jq '.version.number'`  

    version="${version%\"}"
    version="${version#\"}"  

    echo "KIBANA VERSION: ${version}"


    for tenant in "${TENANTS[@]}"; do

      if [ $tenant == "Developer" ]; then
        KIBANA_USER_=$KIBANA_DEVELOPER_USER
        KIBANA_PASSWORD_=$KIBANA_DEVELOPER_PASSWORD
      else
        KIBANA_USER_=$KIBANA_USER
        KIBANA_PASSWORD_=$KIBANA_PASSWORD
      fi  

      
      for i in "${PATTERNS[@]}"; do
        
        if [ "${i}" == "all" ]; then 
          pattern="${i}"
        else
          pattern="${i}-*"
        fi  
        
        check=`curl -s -o /dev/null -w "%{http_code}" -X GET -u$KIBANA_USER_:$KIBANA_PASSWORD_ \
          -H "securitytenant: ${tenant}" $KIBANA_URL/api/saved_objects/index-pattern/${pattern}`
        
        if [ "$check" == "404" ]; then
  
            result=`curl -s -o /dev/null -w "%{http_code}" -X POST -u$KIBANA_USER_:$KIBANA_PASSWORD_ \
              $KIBANA_URL/api/saved_objects/index-pattern/${pattern} \
              -H "securitytenant: ${tenant}" -H "kbn-xsrf: true" -H "Content-Type: application/json" \
              -d "{\"attributes\": {\"title\": \"${pattern}\",\"timeFieldName\": \"@timestamp\"}}"`
            
          if [ "${result}" == "200" ]; then 
            echo "index pattern ${tenant}/${pattern} created successfully"
          else 
            echo "creating index pattern: ${tenant}/${pattern} failed"  
          fi    

        else
          echo "index pattern ${tenant}/${pattern} already exist"
        fi
      
      done  

        
      if [ "${PATTERNS[0]}" == "all" ]; then 
        default="all"
      else
        default="${PATTERNS[0]}-*"
      fi  

      result=`curl -s -o /dev/null -w "%{http_code}" -X PUT -u$KIBANA_USER_:$KIBANA_PASSWORD_ \
          $KIBANA_URL/api/saved_objects/config/${version} \
          -H "securitytenant: ${tenant}" -H "kbn-xsrf: true" -H "Content-Type: application/json" \
          -d "{\"attributes\": {\"defaultIndex\": \"${default}\"}}"` 

      if [ "${result}" == "200" ]; then 
        echo "default index pattern ${tenant}/${default} set successfully"
      else 
        echo "setting default index pattern ${tenant}/${default} failed ${result}"  
      fi    
        
    
        
    echo "Import saved objects ${tenant}"
    for f in /saved_objects/* ; do
      result=`curl -s -o /dev/null -w "%{http_code}" -X POST -u$KIBANA_USER_:$KIBANA_PASSWORD_ \
        $KIBANA_URL/api/saved_objects/_import?overwrite=true \
        -H "securitytenant: ${tenant}" -H "kbn-xsrf: true" --form file=@${f}`
      
      if [ "${result}" == "200" ]; then 
        echo "${f} imported"
      else 
        echo "importing ${f} failed ${result}"  
      fi  
    done
    done