apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name}}-fluent-bit
  labels:
    k8s-app: fluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels: {{ include "logging.selectorLabels" . | indent 6 }}
      k8s-app: fluent-bit-logging
  template:
    metadata:
      labels: {{ include "logging.selectorLabels" . | indent 8 }}
        k8s-app: fluent-bit-logging        
        kubernetes.io/cluster-service: "true"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/fluentbit/fluentbit-config.yaml") . | sha256sum }}  
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: /api/v1/metrics/prometheus
    spec:
      priorityClassName: {{ default .Values.priority_class .Values.fluentbit.priority_class }}
      securityContext:
        runAsUser: 0
      serviceAccountName: {{ .Release.Name}}-fluentbit      
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 6 }}
      {{- end }}
      initContainers:
      - name: init
        imagePullPolicy: {{ .Values.init_container.imagePullPolicy }}
        image: {{ include "init_container.image" . }}
        {{- if .Values.kafka.enabled }}
        command: ["sh","-c",'/init/check_es.sh && /init/check_host_port.sh $kafka 9092']
        {{ else }}
        command: ["sh","-c",'/init/check_es.sh']
        {{- end }}
        env:
          - name: es_url
            value: {{ include "es_url" . }}
          - name: es_user
            value: {{ .Values.elasticsearch.user }}
          - name: es_pass
            value: {{ .Values.elasticsearch.password }}
          - name: kafka
            value: {{ .Release.Name }}-kafka-{{ (sub (.Values.kafka.replicas | int) 1) }}  
        volumeMounts:
        - mountPath: "/init"
          name: init      
      containers:
      - name: fluent-bit
        image: {{ .Values.fluentbit.image }}:{{ .Values.fluentbit.imageTag }}
        imagePullPolicy: Always
        resources: {{ toYaml .Values.fluentbit.resources | nindent 10 }}
        ports:
          - containerPort: 2020
        env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: "{{ include "es_host" . }}"
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "{{ include "es_port" . }}"
        - name: FLUENT_ELASTICSEARCH_USER
          value:  {{ .Values.elasticsearch.user }}
        - name: FLUENT_ELASTICSEARCH_PASSWORD
          value:  {{ .Values.elasticsearch.password }}  
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true  
        - name: journallog
          mountPath: /run/log
          readOnly: true
        - name: fluent-bit-config        
          mountPath: /fluent-bit/etc          
        - name: certificates
          mountPath: /fluent-bit/ssl/root-ca.pem
          subPath: root-ca.pem
        - name: certificates
          mountPath: /fluent-bit/ssl/admin.pem
          subPath: admin.pem  
        - name: certificates
          mountPath: /fluent-bit/ssl/admin-key.pem
          subPath: admin-key.pem          
      terminationGracePeriodSeconds: 10
      volumes:
      - name: init
        configMap:
          name: {{ .Release.Name}}-init
          defaultMode: 0755  
      - name: journallog
        hostPath:
          path: {{ .Values.fluentbit.journal_host_path }}
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: {{ .Release.Name}}-fluent-bit
      - name: certificates
        secret:
          secretName: {{ .Release.Name }}-certificates    
      {{- with .Values.fluentbit.affinity }}     
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fluentbit.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}