apiVersion: v1
kind: Secret
metadata:
  name: logstash-indexer-elasticsearch
type: Opaque
data:
  host: {{ include "es_url" . | b64enc }}
  user: {{ .Values.elasticsearch.user | b64enc }}
  password: {{ .Values.elasticsearch.password | b64enc }}
