apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}-logstash-indexer
  labels: {{ include "logging.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.logstash_indexer.replicas}}
  selector:
    matchLabels: {{ include "logging.metadata.labels" . | indent 6 }}
      type: logstash-indexer
  strategy:
    type: Recreate    
  template:
    metadata:
      annotations:
        checksum1/config: {{ include (print $.Template.BasePath "/logstash/logstash-indexer-configmap.yaml") . | sha256sum }}
        {{- range $path, $_ :=  $.Files.Glob  "logstash-indexer-pipelines/*-pipeline.conf" }}
        {{ $path | printf "checksum-%s"}}: {{ $.Files.Get $path | sha256sum }}
        {{- end }}
      labels: {{ include "logging.metadata.labels" . | indent 8 }}
        type: logstash-indexer
    spec:
      {{- with .Values.logstash_indexer.affinity }}     
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.logstash_indexer.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 6 }}
      {{- end }}
      initContainers:
      - name: init
        image: {{ include "init_container.image" . }}
        imagePullPolicy: {{ .Values.init_container_image.imagePullPolicy }}
        {{- if .Values.kafka.in_cluster }}
        command: 
          - sh
          - -c
          - /init.sh {{ include "esurl" . }} && /init.sh {{ .Release.Name }}-kafka-{{ (sub (.Values.kafka.replicas | int) 1) }}.kafka 9092
        {{ else }}
        command: 
        - sh
        - -c
        - /init.sh {{ include "esurl" . }}
        {{- end }}
        volumeMounts:
        - mountPath: "/init.sh"
          subPath: init.sh
          name: init     
      containers:  
      - name: logstash-indexer
        image: {{ .Values.repository }}/logstash/logstash-oss:{{ .Values.app_version }}
        {{- if not .Values.kafka.enabled }}
        ports:
        - containerPort: 5044
          name: containers
          protocol: TCP
        - containerPort: 5045
          protocol: TCP
          name: journals
        {{- end }}      
        env:
        - name: ELASTICSEARCH_HOST
          valueFrom:
            secretKeyRef:
              name: logstash-indexer-elasticsearch
              key: host            
        {{- if .Values.elasticsearch.user }}
        - name: ELASTICSEARCH_USER
          valueFrom:
            secretKeyRef:
              name: logstash-indexer-elasticsearch
              key: user 
        {{- end }}
        {{- if .Values.elasticsearch.password }}
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: logstash-indexer-elasticsearch
              key: password
        {{- end }}   
        {{- if .Values.kafka.enabled }}           
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka-svc:9092
        {{- end }}          
        - name: LS_JAVA_OPTS
          value: "-Xms{{ .Values.logstash_indexer.heap_size }} -Xmx{{ .Values.logstash_indexer.heap_size }} {{ .Values.elasticsearch.additional_jvm_params }}"
        - name: CA_CERT
          value: "{{ .Values.logstash_indexer.ca_cert }}"
        resources: {{ toYaml .Values.logstash_indexer.resources | nindent 10 }}  
        volumeMounts:
        - mountPath: "/usr/share/logstash/config/logstash.yml"
          subPath: logstash.yml
          name: config
        - mountPath: "/usr/share/logstash/config/pipelines.yml"
          subPath: pipelines.yml
          name: config
        - mountPath: "/usr/share/logstash/config/log4j2.properties"
          subPath: log4j2.properties
          name: config
        {{- range $path, $bytes := .Files.Glob "logstash-indexer-pipelines/*-pipeline.conf" }}
        - mountPath: {{ printf "%s%s" "/usr/share/logstash/pipeline/" (base $path) }}
          subPath: {{ printf "%s" (base $path) }}
          name: pipelines
        {{- end -}}
        {{ range $path, $bytes := .Files.Glob "indices-templates/*_template.json" }}
        - mountPath: {{ printf "%s%s" "/usr/share/logstash/config/" (base $path) }}
          subPath: {{ printf "%s" (base $path) }}
          name: indices-templates
        {{- end }}
        - name: certificates
          mountPath: /usr/share/logstash/config/{{ .Values.logstash_indexer.ca_cert }}
          subPath: {{ .Values.logstash_indexer.ca_cert }}
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name}}-logstash-indexer
      - name: certificates
        secret:
          secretName: {{ .Release.Name }}-certificates
          defaultMode: 0644
      - name: init
        configMap:
          name: {{ .Release.Name}}-init
          defaultMode: 0755    
      - name: pipelines
        configMap:
          name: {{ .Release.Name}}-logstash-indexer-pipelines
      - name: indices-templates
        configMap:
          name: {{ .Release.Name}}-indices-templates
