#Elasticsearch general configuration
elasticsearch:
  single_type_node: false

#Elasticsearch coordination node configuration
client:
  ingress:
    enabled: true
    host: es.local.dev
    annotations:
      nginx.ingress.kubernetes.io/enable-access-log: "true"
      nginx.ingress.kubernetes.io/rewrite-target: "/"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    tls:
      - hosts:
          - es.local.dev
        secretName: es-tls

#Kibana configuration
kibana:
  ingress:
    enabled: true 
    host: kibana.local.dev
    annotations:
      nginx.ingress.kubernetes.io/enable-access-log: "true"
      nginx.ingress.kubernetes.io/affinity: "cookie"
      nginx.ingress.kubernetes.io/session-cookie-name: "security_authentication"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    tls:
      - hosts:
          - kibana.local.dev
        secretName: kibana-tls  
             
#Configuration for containers logs path needs to be adjusted corresponding to the host
filebeat:
  host_path: /var/lib/docker/containers/
  tolerations:
    - operator: "Exists"
      effect: "NoSchedule"

#Configuration for journal logs path needs to be adjusted corresponding to the host
journalbeat:
  enabled: true
  host_path: /run/log/journal
  tolerations:
    - operator: "Exists"
      effect: "NoSchedule"

#Configuration for sys cgroups path needs to be adjusted corresponding to the host      
metricbeat:
  enabled: true
  host_path: "/sys/fs/cgroup"
  tolerations:
    - operator: "Exists"
      effect: "NoSchedule"
#kafka buffering should be enabled in scaled out configuration
kafka:
  enabled: false