#Scaled configuration suitbale for load > 1 000 000 documents per minute
#Each components in the setup is running in HA mode with at least 2 instances
#Runs stable on 3 nodes ( 8 VCPUs and 32GB RAM - ) Standard_D8_v3 - Azure, c5.4xlarge AWS
elasticsearch:
  index_shards: 3
  index_replicas: 1
  retention_days: 7

client:
  replicas: 2
  heap_size: 2g
  resources:
    requests:
      memory: 4Gi
    limits:
      memory: 4Gi

master:
  replicas: 2
  heap_size: 2g
  resources:
    requests:
      memory: 4Gi
    limits:
      memory: 4Gi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: type
            operator: In
            values:
            - master
        topologyKey: kubernetes.io/hostname        
data:
  replicas: 3
  heap_size: 8g
  resources:
    requests:
      memory: 15Gi
    limits:
      memory: 15Gi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: type
            operator: In
            values:
            - data  
        topologyKey: kubernetes.io/hostname        

kafka:
  enabled: true
  replicas: 3
  heap_size: 2g
  resources:
    requests:
      memory: 4Gi
    limits:
      memory: 4Gi
  topics:
    config: "retention.bytes=536870912,retention.ms=43200000,message.timestamp.difference.max.ms=43200000,segment.bytes=209715200,max.message.bytes=15728640,message.timestamp.type=LogAppendTime"
    name: ["containers","journals"]
    replication_factor: 2
    partitions: 5
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: type
            operator: In
            values:
            - kafka  
        topologyKey: kubernetes.io/hostname      

zookeeper:
  replicas: 3
  heap_size: 128M
  resources:
    requests:
      memory: 300Mi
    limits:
      memory: 300Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: type
            operator: In
            values:
            - zk   
        topologyKey: kubernetes.io/hostname     

kibana:
  oldSpaceSize: 2048
  resources:
    requests:
      memory: 3Gi
    limits:
      memory: 3Gi

logstash_indexer:
  replicas: 3
  heap_size: 1g
  resources:
    requests:
      memory: 2Gi
    limits:
      memory: 2Gi 

journalbeat:
  resources:
    requests:
      memory: 250Mi
    limits:
      memory: 250Mi

filebeat:
  resources:
    requests:
      memory: 400Mi
    limits:
      memory: 400Mi