{{- if and .Values.kibana.ingress.enabled .Values.kibana.in_cluster }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-kibana
  labels: {{ include "logging.labels" . | indent 4 }}
  {{- with .Values.kibana.ingress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.kibana.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4}}
  {{- end }}
  rules:
  - host: {{ .Values.kibana.ingress.host }}
    http:
      paths:
      - path: {{ .Values.kibana.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-kibana
            port:
              number: 5601
{{- end }}
