apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: logging
value: 500
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: logging-data
value: 1000
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: logging-beats
value: 10000