---
# In this file users, backendroles and hosts can be mapped to Open Distro Security roles.
# Permissions for Opendistro roles are configured in roles.yml

_meta:
  type: "rolesmapping"
  config_version: 2

# Administrator privileges
all_access:
  reserved: true
  {{- with list .Values.opensearch.saml.admin_role .Values.opensearch.oidc.admin_role "administrator" | mustCompact | mustUniq }}
  backend_roles: {{ . | toYaml | nindent 2 }}
  {{- end }}
  description: "Maps external os user to admin role"

administrator:
  reserved: true
  {{- with list .Values.opensearch.saml.admin_role .Values.opensearch.oidc.admin_role "administrator" | mustCompact | mustUniq }}
  backend_roles: {{ . | toYaml | nindent 2 }}
  {{- end }}
  description: "Maps external os user to admin role"

alerting_full_access:
  reserved: true
  {{- with list .Values.opensearch.saml.admin_role .Values.opensearch.oidc.admin_role "administrator" | mustCompact | mustUniq }}
  backend_roles: {{ . | toYaml | nindent 2 }}
  {{- end }}
  description: "Maps external os user to admin role"

# Viewer - readonly access
opensearch-dashboards_viewer:
  reserved: true
  users:
    - {{ .Values.opensearch_dashboards.readonly.user }}
  {{- with list .Values.opensearch.saml.viewer_role .Values.opensearch.oidc.viewer_role "Viewer" | mustCompact | mustUniq }}
  backend_roles: {{ . | toYaml | nindent 2 }}
  {{- end }}
  description: "Maps viewer backend role"

alerting_view_alerts:
  reserved: true
  users:
    - {{ .Values.opensearch_dashboards.readonly.user }}
  {{- with list .Values.opensearch.saml.viewer_role .Values.opensearch.oidc.viewer_role "Viewer" | mustCompact | mustUniq }}
  backend_roles: {{ . | toYaml | nindent 2 }}
  {{- end }}
  description: "Maps viewer backend role"


# Developer access
opensearch-dashboards_developer:
  reserved: true
  users:
    - {{ .Values.opensearch_dashboards.developer.user }}
  {{- with list .Values.opensearch.saml.developer_role .Values.opensearch.oidc.developer_role "Developer" | mustCompact | mustUniq }}
  backend_roles: {{ . | toYaml | nindent 2 }}
  {{- end }}  
  description: "Maps developer backend role"

alerting_crud_alerts:
  reserved: true
  users:
    - {{ .Values.opensearch_dashboards.developer.user }}
  {{- with list .Values.opensearch.saml.developer_role .Values.opensearch.oidc.developer_role "Developer" | mustCompact | mustUniq }}
  backend_roles: {{ . | toYaml | nindent 2 }}
  {{- end }}
  description: "Maps developer backend role"

# kibana user  access
kibana_user:
  reserved: true
  {{- with list .Values.opensearch.saml.viewer_role .Values.opensearch.oidc.viewer_role .Values.opensearch.saml.developer_role .Values.opensearch.oidc.developer_role "Viewer" "Developer" | mustCompact | mustUniq }}
  backend_roles: {{ . | toYaml | nindent 2 }}
  {{- end }}
  description: "Maps viewer and developer backend roles to opensearch-dashboards_user role"      