{{- if and .Values.kafka.enabled .Values.logstash.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name}}-logstash
  labels: {{ include "logging.labels" . | indent 4 }}
{{- end }}