{{- if .Values.kafka.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  metadata:
  name: {{ .Release.Name }}-zk
  labels: {{ include "logging.labels" . | indent 4 }}
spec:
  selector:
    matchLabels: {{ include "logging.metadata.labels" . | indent 6 }}
      type: zk
  serviceName: zk
  replicas: {{ .Values.zookeeper.replicas }}
  template:
    metadata:
      labels: {{ include "logging.metadata.labels" . | indent 8 }}
        type: zk
    spec:
      priorityClassName: logging-critical
      {{- with .Values.zookeeper.affinity }}     
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.zookeeper.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 6 }}
      {{- end }}
      initContainers:
      - image: {{ include "init_container.image" . }}
        imagePullPolicy: {{ .Values.init_container_image.imagePullPolicy }}
        command: ["sh", "-c", "until mkdir -p /volumes/data /volumes/logs && rm -f /volumes/data/myid && echo ${MY_POD_NAME##*-} > /volumes/data/myid ; do  echo \"retry create data and logs folders\" && sleep 2 ; done"]
        name: init
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - mountPath: "/volumes"
          name: zk-data
      containers:
      - name: zk
        image: zookeeper:{{ .Values.zookeeper.tag }}
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: peer
        - containerPort: 3888
          name: leader
        env:
        - name: ZOO_SERVERS
          value: {{ include "zookeeper_servers" .| quote }}
        - name: ZOO_DATA_DIR
          value: /volumes/data
        - name: ZOO_DATA_LOG_DIR
          value: /volumes/logs
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources: {{ toYaml .Values.zookeeper.resources | nindent 10 }}        
        volumeMounts:
        - mountPath: "/volumes"
          name: zk-data
  volumeClaimTemplates:
  - metadata:
      name: zk-data
    spec:
      {{- with .Values.storage_class }}
      storageClassName: {{ . | quote }}
      {{- end }}
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
{{- end }}          
